module.exports = {
  endpoints: [
    // admin endpoints
    {
      folder: "Admins",
      auth: { type: "bearer", token: "{{adminToken}}" },
      items: [
        {
          folder: "Auth",
          auth: null,
          items: [
            {
              name: "Authenticate",
              method: "POST",
              url: "{{local}}/admin/auth/authenticate",
              bodyType: "raw",
              body: {
                email: "superadmin@gmail.com",
                password: "P@ssw0rd",
              },
              script: {
                type: "test",
                exec: [
                  "const response = pm.response.json();",
                  "if (response.results && response.results.accessToken) {",
                  '    pm.collectionVariables.set("adminToken", response.results.accessToken);',
                  "}",
                ],
              },
              params: [],
            },
            {
              name: "Refresh Token",
              method: "POST",
              url: "{{local}}/admin/auth/refresh-token",
              bodyType: "raw",
              body: {},
              script: {
                type: "test",
                exec: [
                  "const response = pm.response.json();",
                  "if (response.results && response.results.accessToken) {",
                  '    pm.collectionVariables.set("adminToken", response.results.accessToken);',
                  "}",
                ],
              },
              params: [],
            },
            {
              name: "Logout",
              method: "POST",
              url: "{{local}}/admin/auth/logout",
              params: [],
            },
          ],
        },
        {
          folder: "Admins",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/admin/admins",
              params: [
                { key: "page", value: "1", type: "query" },
                { key: "limit", value: "10", type: "query" },
                { key: "sortBy", value: "createdAt", type: "query" },
                { key: "sortDirection", value: "desc", type: "query" },
                { key: "term", value: "", type: "query" },
                { key: "type", value: "", type: "query" },
              ],
            },
            {
              name: "Create",
              method: "POST",
              url: "{{local}}/admin/admins",
              bodyType: "form-data",
              fields: [
                {
                  key: "firstName",
                  value: "John Doe",
                  type: "text",
                },
                {
                  key: "lastName",
                  value: "Doe",
                  type: "text",
                },
                {
                  key: "email",
                  value: "superadmin@gmail.com",
                  type: "text",
                },
                {
                  key: "password",
                  value: "P@ssw0rd",
                  type: "text",
                },
                {
                  key: "type",
                  value: "<id>",
                  type: "text",
                },
                {
                  key: "image",
                  value: "image.png",
                  type: "file",
                },
                {
                  key: "isActive",
                  value: "true",
                  type: "text",
                },
              ],
              params: [],
            },
            {
              name: "Update",
              method: "PUT",
              url: "{{local}}/admin/admins/update",
              bodyType: "form-data",
              fields: [
                {
                  key: "_id",
                  value: "<id>",
                  type: "text",
                },
                {
                  key: "firstName",
                  value: "John Doe",
                  type: "text",
                },
                {
                  key: "lastName",
                  value: "Doe",
                  type: "text",
                },
                {
                  key: "email",
                  value: "superadmin@gmail.com",
                  type: "text",
                },
                {
                  key: "password",
                  value: "P@ssw0rd",
                  type: "text",
                },
                {
                  key: "type",
                  value: "<id>",
                  type: "text",
                },
                {
                  key: "image",
                  value: "image.png",
                  type: "file",
                },
                {
                  key: "isActive",
                  value: "true",
                  type: "text",
                },
              ],
              params: [],
            },
            {
              name: "Delete",
              method: "DELETE",
              url: "{{local}}/admin/admins/delete/:ids",
              params: [],
            },
          ],
        },
        {
          folder: "Admin Types",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/admin/admin-type",
              params: [
                { key: "page", value: "1", type: "query" },
                { key: "limit", value: "10", type: "query" },
              ],
            },
            {
              name: "Create",
              method: "POST",
              url: "{{local}}/admin/admin-type",
              bodyType: "raw",
              body: {
                name: "<string>",
                privileges: {
                  function_id: {
                    read: true,
                    write: true,
                    update: true,
                    delete: true,
                  },
                },
              },
              params: [],
            },
            {
              name: "Update",
              method: "PUT",
              url: "{{local}}/admin/admin-type/update",
              bodyType: "raw",
              body: {
                _id: "<id>",
                name: "<string>",
                privileges: {
                  function_id: {
                    read: true,
                    write: true,
                    update: true,
                    delete: true,
                  },
                },
              },
              params: [],
            },
            {
              name: "Delete",
              method: "DELETE",
              url: "{{local}}/admin/admin-type/delete/:id",
              params: [],
            },
          ],
        },
        {
          folder: "Functions",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/admin/function",
              params: [
                { key: "page", value: "1", type: "query" },
                { key: "limit", value: "10", type: "query" },
              ],
            },
            {
              name: "Create",
              method: "POST",
              url: "{{local}}/admin/function",
              bodyType: "raw",
              body: {
                name: "<string>",
                key: "<string>",
              },
              params: [],
            },
            {
              name: "Delete",
              method: "DELETE",
              url: "{{local}}/admin/function/delete/:id",
              params: [],
            },
          ],
        },
        {
          folder: "User Logs",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/admin/user-log",
              params: [
                { key: "page", value: "1", type: "query" },
                { key: "limit", value: "10", type: "query" },
                { key: "sortBy", value: "createdAt", type: "query" },
                { key: "sortDirection", value: "desc", type: "query" },
                { key: "term", value: "", type: "query" },
                { key: "admin_id", value: "", type: "query" },
              ],
            },
          ],
        },
        {
          folder: "Website",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/admin/website",
              params: [],
            },
            {
              name: "Update",
              method: "PUT",
              url: "{{local}}/admin/website/update",
              bodyType: "form-data",
              fields: [
                {
                  key: "homePage[banner][0][image]",
                  value: "image.png",
                  type: "file",
                },
                {
                  key: "homePage[banner][0][title][en]",
                  value: "title",
                  type: "text",
                },
                {
                  key: "homePage[banner][0][title][ar]",
                  value: "title",
                  type: "text",
                },
                {
                  key: "homePage[banner][0][description][en]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "homePage[banner][0][description][ar]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "homePage[welcomeSection][title][en]",
                  value: "title",
                  type: "text",
                },
                {
                  key: "homePage[welcomeSection][title][ar]",
                  value: "title",
                  type: "text",
                },
                {
                  key: "homePage[welcomeSection][description][en]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "homePage[welcomeSection][description][ar]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "homePage[welcomeSection][featuredServices][0][title][en]",
                  value: "title",
                  type: "text",
                },
                {
                  key: "homePage[welcomeSection][featuredServices][0][title][ar]",
                  value: "title",
                  type: "text",
                },
                {
                  key: "homePage[welcomeSection][featuredServices][0][description][en]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "homePage[welcomeSection][featuredServices][0][description][ar]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "homePage[welcomeSection][featuredServices][0][image]",
                  value: "image.png",
                  type: "file",
                },
                // about page
                {
                  key: "aboutPage[banner]",
                  value: "image.png",
                  type: "file",
                },
                {
                  key: "aboutPage[shortDescription][en]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "aboutPage[shortDescription][ar]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "aboutPage[longDescription][en]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "aboutPage[longDescription][ar]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "aboutPage[mission][title][en]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "aboutPage[mission][title][ar]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "aboutPage[mission][description][en]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "aboutPage[mission][description][ar]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "aboutPage[mission][image]",
                  value: "image.png",
                  type: "file",
                },
                {
                  key: "aboutPage[vision][title][en]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "aboutPage[vision][title][ar]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "aboutPage[vision][description][en]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "aboutPage[vision][description][ar]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "aboutPage[vision][image]",
                  value: "image.png",
                  type: "file",
                },
                {
                  key: "aboutPage[values][title][en]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "aboutPage[values][title][ar]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "aboutPage[values][description][en]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "aboutPage[values][description][ar]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "aboutPage[values][image]",
                  value: "image.png",
                  type: "file",
                },
                {
                  key: "aboutPage[ourSmartApproach][0][title][en]",
                  value: "title",
                  type: "text",
                },
                {
                  key: "aboutPage[ourSmartApproach][0][title][ar]",
                  value: "title",
                  type: "text",
                },
                {
                  key: "aboutPage[ourSmartApproach][0][subTitle][en]",
                  value: "subTitle",
                  type: "text",
                },
                {
                  key: "aboutPage[ourSmartApproach][0][subTitle][ar]",
                  value: "subTitle",
                  type: "text",
                },
                {
                  key: "aboutPage[ourSmartApproach][0][description][en]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "aboutPage[ourSmartApproach][0][description][ar]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "aboutPage[ourSmartApproach][0][image]",
                  value: "image.png",
                  type: "file",
                },
                {
                  key: "aboutPage[oppertunitiesSection][title][en]",
                  value: "title",
                  type: "text",
                },
                {
                  key: "aboutPage[oppertunitiesSection][title][ar]",
                  value: "title",
                  type: "text",
                },
                {
                  key: "aboutPage[oppertunitiesSection][description][en]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "aboutPage[oppertunitiesSection][description][ar]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "aboutPage[oppertunitiesSection][image]",
                  value: "image.png",
                  type: "file",
                },
                {
                  key: "aboutPage[historySection][title][en]",
                  value: "title",
                  type: "text",
                },
                {
                  key: "aboutPage[historySection][title][ar]",
                  value: "title",
                  type: "text",
                },
                {
                  key: "aboutPage[historySection][timeline][0][title][en]",
                  value: "title",
                  type: "text",
                },
                {
                  key: "aboutPage[historySection][timeline][0][title][ar]",
                  value: "title",
                  type: "text",
                },
                {
                  key: "aboutPage[historySection][timeline][0][description][en]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "aboutPage[historySection][timeline][0][description][ar]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "aboutPage[historySection][timeline][0][date]",
                  value: "date",
                  type: "text",
                },
                {
                  key: "aboutPage[historySection][timeline][0][image]",
                  value: "image.png",
                  type: "file",
                },
                // service page
                {
                  key: "servicePage[banner]",
                  value: "image.png",
                  type: "file",
                },
                // blog page
                {
                  key: "blogPage[banner]",
                  value: "image.png",
                  type: "file",
                },
                // project page
                {
                  key: "projectPage[banner]",
                  value: "image.png",
                  type: "file",
                },
                // contact page
                {
                  key: "contactPage[banner]",
                  value: "image.png",
                  type: "file",
                },
              ],
              params: [],
            },
          ],
        },
        {
          folder: "Services",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/admin/service",
              params: [
                { key: "page", value: "1", type: "query" },
                { key: "limit", value: "10", type: "query" },
                { key: "sortBy", value: "createdAt", type: "query" },
                { key: "sortDirection", value: "desc", type: "query" },
                { key: "term", value: "", type: "query" },
              ],
            },
            {
              name: "Find One",
              method: "GET",
              url: "{{local}}/admin/service/:id",
              params: [],
            },
            {
              name: "Create",
              method: "POST",
              url: "{{local}}/admin/service",
              bodyType: "form-data",
              fields: [
                { key: "title[en]", value: "title", type: "text" },
                { key: "title[ar]", value: "title", type: "text" },
                {
                  key: "shortDescription[en]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "shortDescription[ar]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "longDescription[en]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "longDescription[ar]",
                  value: "description",
                  type: "text",
                },
                { key: "banner", value: "image.png", type: "file" },
                { key: "image", value: "image.png", type: "file" },
                { key: "icon", value: "icon", type: "text" },
                {
                  key: "subServices[0][title][en]",
                  value: "title",
                  type: "text",
                },
                {
                  key: "subServices[0][title][ar]",
                  value: "title",
                  type: "text",
                },
                {
                  key: "subServices[0][description][en]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "subServices[0][description][ar]",
                  value: "description",
                  type: "text",
                },
                { key: "subServices[0][icon]", value: "icon", type: "text" },
                {
                  key: "benefits[description][en]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "benefits[description][ar]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "benefits[features][0]",
                  value: "feature",
                  type: "text",
                },
                {
                  key: "benefits[features][1]",
                  value: "feature",
                  type: "text",
                },
                {
                  key: "benefits[video]",
                  value: "video.mp4",
                  type: "text",
                },
                {
                  key: "brochure[pdf]",
                  value: "brochure.pdf",
                  type: "file",
                },
                {
                  key: "brochure[document]",
                  value: "brochure.docx",
                  type: "file",
                },
                {
                  key: "isActive",
                  value: "true",
                  type: "text",
                },
              ],
              params: [],
            },
            {
              name: "Update",
              method: "PUT",
              url: "{{local}}/admin/service/update",
              bodyType: "form-data",
              fields: [
                { key: "_id", value: "id", type: "text" },
                { key: "title[en]", value: "title", type: "text" },
                { key: "title[ar]", value: "title", type: "text" },
                {
                  key: "shortDescription[en]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "shortDescription[ar]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "longDescription[en]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "longDescription[ar]",
                  value: "description",
                  type: "text",
                },
                { key: "banner", value: "image.png", type: "file" },
                { key: "image", value: "image.png", type: "file" },
                { key: "icon", value: "icon", type: "text" },
                {
                  key: "subServices[0][title][en]",
                  value: "title",
                  type: "text",
                },
                {
                  key: "subServices[0][title][ar]",
                  value: "title",
                  type: "text",
                },
                {
                  key: "subServices[0][description][en]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "subServices[0][description][ar]",
                  value: "description",
                  type: "text",
                },
                { key: "subServices[0][icon]", value: "icon", type: "text" },
                {
                  key: "benefits[description][en]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "benefits[description][ar]",
                  value: "description",
                  type: "text",
                },
                {
                  key: "benefits[features][0]",
                  value: "feature",
                  type: "text",
                },
                {
                  key: "benefits[features][1]",
                  value: "feature",
                  type: "text",
                },
                {
                  key: "benefits[video]",
                  value: "video.mp4",
                  type: "text",
                },
                {
                  key: "brochure[pdf]",
                  value: "brochure.pdf",
                  type: "file",
                },
                {
                  key: "brochure[document]",
                  value: "brochure.docx",
                  type: "file",
                },
                {
                  key: "isActive",
                  value: "true",
                  type: "text",
                },
              ],
              params: [],
            },
            {
              name: "Delete",
              method: "DELETE",
              url: "{{local}}/admin/service/delete/:ids",
              params: [],
            },
          ],
        },
        {
          folder: "Settings",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/admin/setting",
              params: [],
            },
            {
              name: "Update",
              method: "PUT",
              url: "{{local}}/admin/setting/update",
              bodyType: "form-data",
              fields: [
                { key: "contact[email]", value: "email", type: "text" },
                {
                  key: "contact[phone][number]",
                  value: "phone.number",
                  type: "text",
                },
                {
                  key: "contact[phone][code]",
                  value: "phone.code",
                  type: "text",
                },
                { key: "contact[address]", value: "address", type: "text" },
                { key: "contact[map]", value: "map", type: "text" },
                { key: "social[facebook]", value: "facebook", type: "text" },
                { key: "social[instagram]", value: "instagram", type: "text" },
                { key: "social[twitter]", value: "twitter", type: "text" },
                { key: "social[linkedin]", value: "linkedin", type: "text" },
                { key: "social[youtube]", value: "youtube", type: "text" },
                { key: "social[tiktok]", value: "tiktok", type: "text" },
                {
                  key: "contactTeam[0][name][en]",
                  value: "name",
                  type: "text",
                },
                {
                  key: "contactTeam[0][name][ar]",
                  value: "name",
                  type: "text",
                },
                {
                  key: "contactTeam[0][position][en]",
                  value: "position",
                  type: "text",
                },
                {
                  key: "contactTeam[0][position][ar]",
                  value: "position",
                  type: "text",
                },
                {
                  key: "contactTeam[0][image]",
                  value: "image.png",
                  type: "file",
                },
                {
                  key: "contactTeam[0][phone][number]",
                  value: "phone.number",
                  type: "text",
                },
                {
                  key: "contactTeam[0][phone][code]",
                  value: "phone.code",
                  type: "text",
                },
                { key: "contactTeam[0][email]", value: "email", type: "text" },
              ],
              params: [],
            },
          ],
        },
        {
          folder: "Testimonials",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/admin/testimonial",
              params: [
                { key: "page", value: "1", type: "query" },
                { key: "limit", value: "10", type: "query" },
                { key: "sortBy", value: "createdAt", type: "query" },
                { key: "sortDirection", value: "desc", type: "query" },
                { key: "term", value: "", type: "query" },
              ],
            },
            {
              name: "Find One",
              method: "GET",
              url: "{{local}}/admin/testimonial/:id",
              params: [],
            },
            {
              name: "Create",
              method: "POST",
              url: "{{local}}/admin/testimonial",
              bodyType: "raw",
              body: {
                name: {
                  en: "<string>",
                  ar: "<string>",
                },
                position: {
                  en: "<string>",
                  ar: "<string>",
                },
                description: {
                  en: "<string>",
                  ar: "<string>",
                },
                isActive: "true",
              },
              params: [],
            },
            {
              name: "Update",
              method: "PUT",
              url: "{{local}}/admin/testimonial/update",
              bodyType: "raw",
              body: {
                _id: "<id>",
                name: {
                  en: "<string>",
                  ar: "<string>",
                },
                position: {
                  en: "<string>",
                  ar: "<string>",
                },
                description: {
                  en: "<string>",
                  ar: "<string>",
                },
                isActive: "true",
              },
              params: [],
            },
            {
              name: "Delete",
              method: "DELETE",
              url: "{{local}}/admin/testimonial/delete/:ids",
              params: [],
            },
          ],
        },
        {
          folder: "FAQs",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/admin/faq",
              params: [
                { key: "page", value: "1", type: "query" },
                { key: "limit", value: "10", type: "query" },
                { key: "sortBy", value: "createdAt", type: "query" },
                { key: "sortDirection", value: "desc", type: "query" },
                { key: "term", value: "", type: "query" },
              ],
            },
            {
              name: "Find One",
              method: "GET",
              url: "{{local}}/admin/faq/:id",
              params: [],
            },
            {
              name: "Create",
              method: "POST",
              url: "{{local}}/admin/faq",
              bodyType: "raw",
              body: {
                question: {
                  en: "<string>",
                  ar: "<string>",
                },
                answer: {
                  en: "<string>",
                  ar: "<string>",
                },
                isActive: "true",
              },
              params: [],
            },
            {
              name: "Update",
              method: "PUT",
              url: "{{local}}/admin/faq/update",
              bodyType: "raw",
              body: {
                _id: "<id>",
                question: {
                  en: "<string>",
                  ar: "<string>",
                },
                answer: {
                  en: "<string>",
                  ar: "<string>",
                },
                isActive: "true",
              },
              params: [],
            },
            {
              name: "Delete",
              method: "DELETE",
              url: "{{local}}/admin/faq/delete/:ids",
              params: [],
            },
          ],
        },
        {
          folder: "Partners",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/admin/partner",
              params: [
                { key: "page", value: "1", type: "query" },
                { key: "limit", value: "10", type: "query" },
                { key: "sortBy", value: "createdAt", type: "query" },
                { key: "sortDirection", value: "desc", type: "query" },
                { key: "term", value: "", type: "query" },
              ],
            },
            {
              name: "Find One",
              method: "GET",
              url: "{{local}}/admin/partner/:id",
              params: [],
            },
            {
              name: "Create",
              method: "POST",
              url: "{{local}}/admin/partner",
              bodyType: "form-data",
              fields: [
                { key: "title[en]", value: "title", type: "text" },
                { key: "title[ar]", value: "title", type: "text" },
                { key: "image", value: "image.png", type: "file" },
                { key: "isActive", value: "true", type: "text" },
              ],
              params: [],
            },
            {
              name: "Update",
              method: "PUT",
              url: "{{local}}/admin/partner/update",
              bodyType: "form-data",
              fields: [
                { key: "_id", value: "id", type: "text" },
                { key: "title[en]", value: "title", type: "text" },
                { key: "title[ar]", value: "title", type: "text" },
                { key: "image", value: "image.png", type: "file" },
                { key: "isActive", value: "true", type: "text" },
              ],
              params: [],
            },
            {
              name: "Delete",
              method: "DELETE",
              url: "{{local}}/admin/partner/delete/:ids",
              params: [],
            },
          ],
        },
        {
          folder: "Blogs",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/admin/blog",
              params: [
                { key: "page", value: "1", type: "query" },
                { key: "limit", value: "10", type: "query" },
                { key: "sortBy", value: "createdAt", type: "query" },
                { key: "sortDirection", value: "desc", type: "query" },
                { key: "term", value: "", type: "query" },
                { key: "service", value: "", type: "query" },
                { key: "tags", value: "", type: "query" },
              ],
            },
            {
              name: "Find One",
              method: "GET",
              url: "{{local}}/admin/blog/:id",
              params: [],
            },
            {
              name: "Create",
              method: "POST",
              url: "{{local}}/admin/blog",
              bodyType: "form-data",
              fields: [
                { key: "title[en]", value: "title", type: "text" },
                { key: "title[ar]", value: "title", type: "text" },
                { key: "subTitle[en]", value: "subTitle", type: "text" },
                { key: "subTitle[ar]", value: "subTitle", type: "text" },
                { key: "description[en]", value: "description", type: "text" },
                { key: "description[ar]", value: "description", type: "text" },
                { key: "image", value: "image.png", type: "file" },
                { key: "service", value: "", type: "text" },
                { key: "author", value: "", type: "text" },
                { key: "tags[0]", value: "", type: "text" },
                { key: "tags[1]", value: "", type: "text" },
                { key: "tags[2]", value: "", type: "text" },
                { key: "isActive", value: "true", type: "text" },
              ],
              params: [],
            },
            {
              name: "Update",
              method: "PUT",
              url: "{{local}}/admin/blog/update",
              bodyType: "form-data",
              fields: [
                { key: "_id", value: "id", type: "text" },
                { key: "title[en]", value: "title", type: "text" },
                { key: "title[ar]", value: "title", type: "text" },
                { key: "subTitle[en]", value: "subTitle", type: "text" },
                { key: "subTitle[ar]", value: "subTitle", type: "text" },
                { key: "description[en]", value: "description", type: "text" },
                { key: "description[ar]", value: "description", type: "text" },
                { key: "image", value: "image.png", type: "file" },
                { key: "service", value: "", type: "text" },
                { key: "author", value: "", type: "text" },
                { key: "tags[0]", value: "", type: "text" },
                { key: "tags[1]", value: "", type: "text" },
                { key: "tags[2]", value: "", type: "text" },
                { key: "isActive", value: "true", type: "text" },
              ],
              params: [],
            },
            {
              name: "Delete",
              method: "DELETE",
              url: "{{local}}/admin/blog/delete/:ids",
              params: [],
            },
          ],
        },
        {
          folder: "Contacts",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/admin/contact",
              params: [
                { key: "page", value: "1", type: "query" },
                { key: "limit", value: "10", type: "query" },
                { key: "sortBy", value: "createdAt", type: "query" },
                { key: "sortDirection", value: "desc", type: "query" },
                { key: "term", value: "", type: "query" },
                { key: "isRead", value: "", type: "query" },
              ],
            },
            {
              name: "Find One",
              method: "GET",
              url: "{{local}}/admin/contact/:id",
              params: [],
            },
            {
              name: "Update",
              method: "PUT",
              url: "{{local}}/admin/contact/update",
              bodyType: "raw",
              body: {
                _id: "<id>",
                isRead: "true",
              },
              params: [],
            },
            {
              name: "Delete",
              method: "DELETE",
              url: "{{local}}/admin/contact/delete/:ids",
              params: [],
            },
          ],
        },
        {
          folder: "Projects",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/admin/project",
              params: [
                { key: "page", value: "1", type: "query" },
                { key: "limit", value: "10", type: "query" },
                { key: "sortBy", value: "createdAt", type: "query" },
                { key: "sortDirection", value: "desc", type: "query" },
                { key: "term", value: "", type: "query" },
                { key: "service", value: "", type: "query" },
                { key: "tags", value: "", type: "query" },
                { key: "isActive", value: "", type: "query" },
              ],
            },
            {
              name: "Find One",
              method: "GET",
              url: "{{local}}/admin/project/:id",
              params: [],
            },
            {
              name: "Create",
              method: "POST",
              url: "{{local}}/admin/project",
              bodyType: "form-data",
              fields: [
                { key: "title[en]", value: "title", type: "text" },
                { key: "title[ar]", value: "title", type: "text" },
                {
                  key: "shortDescription[en]",
                  value: "shortDescription",
                  type: "text",
                },
                {
                  key: "shortDescription[ar]",
                  value: "shortDescription",
                  type: "text",
                },
                { key: "image", value: "image.png", type: "file" },
                { key: "service", value: "", type: "text" },
                { key: "customer", value: "", type: "text" },
                { key: "link", value: "", type: "text" },
                {
                  key: "projectAnalysis[en]",
                  value: "projectAnalysis",
                  type: "text",
                },
                {
                  key: "projectAnalysis[ar]",
                  value: "projectAnalysis",
                  type: "text",
                },
                {
                  key: "projectSolutions[en]",
                  value: "projectSolutions",
                  type: "text",
                },
                {
                  key: "projectSolutions[ar]",
                  value: "projectSolutions",
                  type: "text",
                },
                {
                  key: "projectResults[en]",
                  value: "projectResults",
                  type: "text",
                },
                {
                  key: "projectResults[ar]",
                  value: "projectResults",
                  type: "text",
                },
                { key: "date", value: "", type: "text" },
                { key: "tags[0]", value: "", type: "text" },
                { key: "tags[1]", value: "", type: "text" },
                { key: "tags[2]", value: "", type: "text" },
                { key: "isActive", value: "true", type: "text" },
              ],
              params: [],
            },
            {
              name: "Update",
              method: "PUT",
              url: "{{local}}/admin/project/update",
              bodyType: "form-data",
              fields: [
                { key: "_id", value: "id", type: "text" },
                { key: "title[en]", value: "title", type: "text" },
                { key: "title[ar]", value: "title", type: "text" },
                {
                  key: "shortDescription[en]",
                  value: "shortDescription",
                  type: "text",
                },
                {
                  key: "shortDescription[ar]",
                  value: "shortDescription",
                  type: "text",
                },
                { key: "image", value: "image.png", type: "file" },
                { key: "service", value: "", type: "text" },
                { key: "customer", value: "", type: "text" },
                { key: "link", value: "", type: "text" },
                {
                  key: "projectAnalysis[en]",
                  value: "projectAnalysis",
                  type: "text",
                },
                {
                  key: "projectAnalysis[ar]",
                  value: "projectAnalysis",
                  type: "text",
                },
                {
                  key: "projectSolutions[en]",
                  value: "projectSolutions",
                  type: "text",
                },
                {
                  key: "projectSolutions[ar]",
                  value: "projectSolutions",
                  type: "text",
                },
                {
                  key: "projectResults[en]",
                  value: "projectResults",
                  type: "text",
                },
                {
                  key: "projectResults[ar]",
                  value: "projectResults",
                  type: "text",
                },
                { key: "date", value: "", type: "text" },
                { key: "tags[0]", value: "", type: "text" },
                { key: "tags[1]", value: "", type: "text" },
                { key: "tags[2]", value: "", type: "text" },
                { key: "isActive", value: "true", type: "text" },
              ],
              params: [],
            },
            {
              name: "Delete",
              method: "DELETE",
              url: "{{local}}/admin/project/delete/:ids",
              params: [],
            },
          ],
        },
        {
          folder: "Teams",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/admin/team",
              params: [
                { key: "page", value: "1", type: "query" },
                { key: "limit", value: "10", type: "query" },
                { key: "sortBy", value: "createdAt", type: "query" },
                { key: "sortDirection", value: "desc", type: "query" },
                { key: "term", value: "", type: "query" },
              ],
            },
            {
              name: "Find One",
              method: "GET",
              url: "{{local}}/admin/team/:id",
              params: [],
            },
            {
              name: "Create",
              method: "POST",
              url: "{{local}}/admin/team",
              bodyType: "form-data",
              fields: [
                { key: "name[en]", value: "name", type: "text" },
                { key: "name[ar]", value: "name", type: "text" },
                { key: "position[en]", value: "position", type: "text" },
                { key: "position[ar]", value: "position", type: "text" },
                { key: "image", value: "image.png", type: "file" },
                { key: "description[en]", value: "description", type: "text" },
                { key: "description[ar]", value: "description", type: "text" },
                { key: "phone[code]", value: "phone.code", type: "text" },
                { key: "phone[number]", value: "phone.number", type: "text" },
                { key: "email", value: "", type: "text" },
                {
                  key: "social[facebook]",
                  value: "social.facebook",
                  type: "text",
                },
                {
                  key: "social[instagram]",
                  value: "social.instagram",
                  type: "text",
                },
                {
                  key: "social[linkedin]",
                  value: "social.linkedin",
                  type: "text",
                },
                {
                  key: "social[twitter]",
                  value: "social.twitter",
                  type: "text",
                },
                { key: "isActive", value: "true", type: "text" },
              ],
              params: [],
            },
            {
              name: "Update",
              method: "PUT",
              url: "{{local}}/admin/team/update",
              bodyType: "form-data",
              fields: [
                { key: "_id", value: "id", type: "text" },
                { key: "name[en]", value: "name", type: "text" },
                { key: "name[ar]", value: "name", type: "text" },
                { key: "position[en]", value: "position", type: "text" },
                { key: "position[ar]", value: "position", type: "text" },
                { key: "image", value: "image.png", type: "file" },
                { key: "description[en]", value: "description", type: "text" },
                { key: "description[ar]", value: "description", type: "text" },
                { key: "phone[code]", value: "phone.code", type: "text" },
                { key: "phone[number]", value: "phone.number", type: "text" },
                { key: "email", value: "", type: "text" },
                {
                  key: "social[facebook]",
                  value: "social.facebook",
                  type: "text",
                },
                {
                  key: "social[instagram]",
                  value: "social.instagram",
                  type: "text",
                },

                {
                  key: "social[linkedin]",
                  value: "social.linkedin",
                  type: "text",
                },

                {
                  key: "social[twitter]",
                  value: "social.twitter",
                  type: "text",
                },
                { key: "isActive", value: "true", type: "text" },
              ],
              params: [],
            },
            {
              name: "Delete",
              method: "DELETE",
              url: "{{local}}/admin/team/delete/:ids",
              params: [],
            },
          ],
        },
      ],
    },
    {
      folder: "Public",
      auth: null,
      items: [
        {
          folder: "Services",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/public/service",
              params: [
                { key: "page", value: "1", type: "query" },
                { key: "limit", value: "10", type: "query" },
                { key: "sortBy", value: "createdAt", type: "query" },
                { key: "sortDirection", value: "desc", type: "query" },
                { key: "term", value: "", type: "query" },
              ],
            },
            {
              name: "Find One",
              method: "GET",
              url: "{{local}}/public/service/:slug",
              params: [],
            },
          ],
        },
        {
          folder: "Website",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/public/website",
              params: [],
            },
          ],
        },
        {
          folder: "Settings",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/public/setting",
              params: [],
            },
          ],
        },
        {
          folder: "Testimonials",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/public/testimonial",
              params: [
                { key: "page", value: "1", type: "query" },
                { key: "limit", value: "10", type: "query" },
                { key: "sortBy", value: "createdAt", type: "query" },
                { key: "sortDirection", value: "desc", type: "query" },
                { key: "term", value: "", type: "query" },
              ],
            },
          ],
        },
        {
          folder: "FAQs",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/public/faq",
              params: [
                { key: "page", value: "1", type: "query" },
                { key: "limit", value: "10", type: "query" },
                { key: "sortBy", value: "createdAt", type: "query" },
                { key: "sortDirection", value: "desc", type: "query" },
                { key: "term", value: "", type: "query" },
              ],
            },
          ],
        },
        {
          folder: "Partners",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/public/partner",
              params: [
                { key: "page", value: "1", type: "query" },
                { key: "limit", value: "10", type: "query" },
                { key: "sortBy", value: "createdAt", type: "query" },
                { key: "sortDirection", value: "desc", type: "query" },
                { key: "term", value: "", type: "query" },
              ],
            },
          ],
        },
        {
          folder: "Blogs",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/public/blog",
              params: [
                { key: "page", value: "1", type: "query" },
                { key: "limit", value: "10", type: "query" },
                { key: "sortBy", value: "createdAt", type: "query" },
                { key: "sortDirection", value: "desc", type: "query" },
                { key: "term", value: "", type: "query" },
                { key: "service", value: "", type: "query" },
                { key: "tags", value: "", type: "query" },
              ],
            },
            {
              name: "Find One",
              method: "GET",
              url: "{{local}}/public/blog/:slug",
              params: [],
            },
          ],
        },
        {
          folder: "Contacts",
          auth: null,
          items: [
            {
              name: "Create",
              method: "POST",
              url: "{{local}}/public/contact",
              bodyType: "raw",
              body: {
                fullName: "<string>",
                email: "<string>",
                subject: "<string>",
                message: "<string>",
                phone: {
                  code: "<string>",
                  number: "<string>",
                },
              },
              params: [],
            },
          ],
        },
        {
          folder: "Projects",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/public/project",
              params: [
                { key: "page", value: "1", type: "query" },
                { key: "limit", value: "10", type: "query" },
                { key: "sortBy", value: "createdAt", type: "query" },
                { key: "sortDirection", value: "desc", type: "query" },
                { key: "term", value: "", type: "query" },
                { key: "service", value: "", type: "query" },
                { key: "tags", value: "", type: "query" },
              ],
            },
            {
              name: "Find One",
              method: "GET",
              url: "{{local}}/public/project/:slug",
              params: [],
            },
          ],
        },
        {
          folder: "Teams",
          auth: null,
          items: [
            {
              name: "Find Many",
              method: "GET",
              url: "{{local}}/public/team",
              params: [
                { key: "page", value: "1", type: "query" },
                { key: "limit", value: "10", type: "query" },
                { key: "sortBy", value: "createdAt", type: "query" },
                { key: "sortDirection", value: "desc", type: "query" },
                { key: "term", value: "", type: "query" },
              ],
            },
            {
              name: "Find One",
              method: "GET",
              url: "{{local}}/public/team/:id",
              params: [],
            },
          ],
        },
      ],
    },
  ],
};
