module.exports = {
  admins: "admins",
  adminTypes: "adminTypes",
  userLogs: "userLogs",
  settings: "settings",
  website: "website",
  services: "services",
  testimonials: "testimonials",
  faqs: "faqs",
  partners: "partners",
  blogs: "blogs",
  contacts: "contacts",
  projects: "projects",
  teams: "teams",
  newsletters: "newsletters",
};
